using Entities.Concrete;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Collections.Generic;

namespace DataAccess.Concrete.Configurations
{
    public class TranslateEntityConfiguration : BaseConfiguration<Translate>
    {
        public override void Configure(EntityTypeBuilder<Translate> builder)
        {
            builder.Property(x => x.LangId).IsRequired();
            builder.Property(x => x.Code).HasMaxLength(50).IsRequired();
            builder.Property(x => x.Value).HasMaxLength(500).IsRequired();
            builder.HasData(GetTranslates());

            base.Configure(builder);
        }

        private List<Translate> GetTranslates()
        {
            return new List<Translate>()
            {
            new Translate { Id = 1, LangId = 1, Code = "Login", Value = "Giriş" },
            new Translate { Id = 2, LangId = 1, Code = "Email", Value = "E posta" },
            new Translate { Id = 3, LangId = 1, Code = "Password", Value = "Parola" },
            new Translate { Id = 4, LangId = 1, Code = "Update", Value = "Güncelle" },
            new Translate { Id = 5, LangId = 1, Code = "Delete", Value = "Sil" },
            new Translate { Id = 6, LangId = 1, Code = "UsersGroups", Value = "Kullanıcının Grupları" },
            new Translate { Id = 7, LangId = 1, Code = "UsersClaims", Value = "Kullanıcının Yetkileri" },
            new Translate { Id = 8, LangId = 1, Code = "Create", Value = "Yeni" },
            new Translate { Id = 9, LangId = 1, Code = "Users", Value = "Kullanıcılar" },
            new Translate { Id = 10, LangId = 1, Code = "Groups", Value = "Gruplar" },
            new Translate { Id = 21, LangId = 1, Code = "OperationClaim", Value = "Operasyon Yetkileri" },
            new Translate { Id = 23, LangId = 1, Code = "Languages", Value = "Diller" },
            new Translate { Id = 25, LangId = 1, Code = "TranslateWords", Value = "Dil Çevirileri" },
            new Translate { Id = 27, LangId = 1, Code = "Management", Value = "Yönetim" },
            new Translate { Id = 29, LangId = 1, Code = "AppMenu", Value = "Uygulama" },
            new Translate { Id = 31, LangId = 1, Code = "Added", Value = "Başarıyla Eklendi." },
            new Translate { Id = 33, LangId = 1, Code = "Updated", Value = "Başarıyla Güncellendi." },
            new Translate { Id = 35, LangId = 1, Code = "Deleted", Value = "Başarıyla Silindi." },
            new Translate { Id = 41, LangId = 1, Code = "CouldNotBeVerifyCid", Value = "Kimlik No Doğrulanamadı." },
            new Translate { Id = 43, LangId = 1, Code = "VerifyCid", Value = "Kimlik No Doğrulandı." },
            new Translate { Id = 51, LangId = 1, Code = "SuccessfulLogin", Value = "Sisteme giriş başarılı." },
            new Translate { Id = 59, LangId = 1, Code = "CID", Value = "Vatandaşlık No" },
            new Translate { Id = 61, LangId = 1, Code = "PasswordEmpty", Value = "Parola boş olamaz!" },
            new Translate { Id = 69, LangId = 1, Code = "PasswordDigit", Value = "En Az 1 Rakam İçermelidir!" },
            new Translate { Id = 75, LangId = 1, Code = "InvalidCode", Value = "Geçersiz Bir Kod Girdiniz!" },
            new Translate { Id = 83, LangId = 1, Code = "Unknown", Value = "Bilinmiyor!" },
            new Translate { Id = 85, LangId = 1, Code = "NewPassword", Value = "Yeni Parola:" },
            new Translate { Id = 87, LangId = 1, Code = "ChangePassword", Value = "Parola Değiştir" },
            new Translate { Id = 89, LangId = 1, Code = "Save", Value = "Kaydet" },
            new Translate { Id = 91, LangId = 1, Code = "GroupName", Value = "Grup Adı" },
            new Translate { Id = 93, LangId = 1, Code = "FullName", Value = "Tam Adı" },
            new Translate { Id = 95, LangId = 1, Code = "Address", Value = "Adres" },
            new Translate { Id = 97, LangId = 1, Code = "Notes", Value = "Notlar" },
            new Translate { Id = 99, LangId = 1, Code = "ConfirmPassword", Value = "Parolayı Doğrula" },
            new Translate { Id = 101, LangId = 1, Code = "Code", Value = "Kod" },
            new Translate { Id = 103, LangId = 1, Code = "Alias", Value = "Görünen Ad" },
            new Translate { Id = 105, LangId = 1, Code = "Description", Value = "Açıklama" },
            new Translate { Id = 107, LangId = 1, Code = "Value", Value = "Değer" },
            new Translate { Id = 109, LangId = 1, Code = "LangCode", Value = "Dil Kodu" },
            new Translate { Id = 111, LangId = 1, Code = "Name", Value = "Adı" },
            new Translate { Id = 113, LangId = 1, Code = "MobilePhones", Value = "Cep Telefonu" },
            new Translate { Id = 115, LangId = 1, Code = "NoRecordsFound", Value = "Kayıt Bulunamadı" },
            new Translate { Id = 117, LangId = 1, Code = "Required", Value = "Bu alan zorunludur!" },
            new Translate { Id = 119, LangId = 1, Code = "Permissions", Value = "Permissions" },
            new Translate { Id = 121, LangId = 1, Code = "GroupList", Value = "Grup Listesi" },
            new Translate { Id = 123, LangId = 1, Code = "GrupPermissions", Value = "Grup Yetkileri" },
            new Translate { Id = 125, LangId = 1, Code = "Add", Value = "Ekle" },
            new Translate { Id = 127, LangId = 1, Code = "UserList", Value = "Kullanıcı Listesi" },
            new Translate { Id = 129, LangId = 1, Code = "OperationClaimList", Value = "Yetki Listesi" },
            new Translate { Id = 131, LangId = 1, Code = "LanguageList", Value = "Dil Listesi" },
            new Translate { Id = 133, LangId = 1, Code = "TranslateList", Value = "Dil Çeviri Listesi" },
            new Translate { Id = 135, LangId = 1, Code = "LogList", Value = "İşlem Kütüğü" },
            new Translate { Id = 137, LangId = 1, Code = "DeleteConfirm", Value = "Emin misiniz?" },
            new Translate { Id = 139, LangId = 1, Code = "AppName", Value = "Flutter DevArchitecture" },
            new Translate { Id = 177, LangId = 1, Code = "OperationClaimExists", Value = "Bu operasyon izni zaten mevcut." },
            new Translate { Id = 179, LangId = 1, Code = "StringLengthMustBeGreaterThanThree", Value = "Lütfen En Az 3 Karakterden Oluşan Bir İfade Girin." },
            new Translate { Id = 185, LangId = 1, Code = "AuthorizationsDenied", Value = "Yetkiniz olmayan bir alana girmeye çalıştığınız tespit edildi." },
            new Translate { Id = 187, LangId = 1, Code = "UserNotFound", Value = "Kimlik Bilgileri Doğrulanamadı. Lütfen Yeni Kayıt Ekranını kullanın." },
            new Translate { Id = 189, LangId = 1, Code = "PasswordError", Value = "Kimlik Bilgileri Doğrulanamadı, Kullanıcı adı ve/veya parola hatalı." },
            new Translate { Id = 193, LangId = 1, Code = "SendMobileCode", Value = "Lütfen Size SMS Olarak Gönderilen Kodu Girin!" },
            new Translate { Id = 195, LangId = 1, Code = "NameAlreadyExist", Value = "Oluşturmaya Çalıştığınız Nesne Zaten Var." },
            new Translate { Id = 197, LangId = 1, Code = "WrongCitizenId", Value = "Vatandaşlık No Sistemimizde Bulunamadı. Lütfen Yeni Kayıt Oluşturun!" },
            new Translate { Id = 199, LangId = 1, Code = "CitizenNumber", Value = "Vatandaşlık No" },
            new Translate { Id = 203, LangId = 1, Code = "PasswordLength", Value = "Minimum 8 Karakter Uzunluğunda Olmalıdır!" },
            new Translate { Id = 205, LangId = 1, Code = "PasswordUppercaseLetter", Value = "En Az 1 Büyük Harf İçermelidir!" },
            new Translate { Id = 207, LangId = 1, Code = "PasswordLowercaseLetter", Value = "En Az 1 Küçük Harf İçermelidir!" },
            new Translate { Id = 211, LangId = 1, Code = "PasswordSpecialCharacter", Value = "En Az 1 Simge İçermelidir!" },
            new Translate { Id = 213, LangId = 1, Code = "SendPassword", Value = "Yeni Parolanız E-Posta Adresinize Gönderildi." },
            new Translate { Id = 217, LangId = 1, Code = "SmsServiceNotFound", Value = "SMS Servisine Ulaşılamıyor." },
            new Translate { Id = 219, LangId = 1, Code = "TrueButCellPhone", Value = "Bilgiler doğru. Cep telefonu gerekiyor." },
            new Translate { Id = 221, LangId = 1, Code = "TokenProviderException", Value = "Token Provider boş olamaz!" },
            new Translate { Id = 277, LangId = 1, Code = "CantBeEmpty", Value = "boş bırakılamaz!" },
            new Translate { Id = 279, LangId = 1, Code = "InvalidEmail", Value = "Lütfen geçerli bir e-posta giriniz!" },
            new Translate { Id = 281, LangId = 1, Code = "InvalidPassword", Value = "Lütfen geçerli bir parola giriniz!" },
            new Translate { Id = 283, LangId = 1, Code = "Status", Value = "Durum" },
            new Translate { Id = 285, LangId = 1, Code = "UpdateUser", Value = "Kullanıcı bilgilerini düzenle" },
            new Translate { Id = 287, LangId = 1, Code = "PageNotFound", Value = "Sayfa bulunamadı!" },
            new Translate { Id = 289, LangId = 1, Code = "Loading", Value = "Gerekli işlemler yapılıyor" },
            new Translate { Id = 291, LangId = 1, Code = "HomePage", Value = "Anasayfa" },
            new Translate { Id = 293, LangId = 1, Code = "ReturnHomePage", Value = "Anasayfaya Geri Dön" },
            new Translate { Id = 295, LangId = 1, Code = "Categories", Value = "Kategoriler" },
            new Translate { Id = 297, LangId = 1, Code = "Sells", Value = "Satışlar" },
            new Translate { Id = 299, LangId = 1, Code = "Days", Value = "Günler" },
            new Translate { Id = 301, LangId = 1, Code = "Sales", Value = "Satışlar" },
            new Translate { Id = 305, LangId = 1, Code = "Months", Value = "Aylar" },
            new Translate { Id = 307, LangId = 1, Code = "Years", Value = "Yıllar" },
            new Translate { Id = 309, LangId = 1, Code = "Hours", Value = "Saatler" },
            new Translate { Id = 311, LangId = 1, Code = "Minutes", Value = "Dakikalar" },
            new Translate { Id = 313, LangId = 1, Code = "Seconds", Value = "Saniyeler" },
            new Translate { Id = 315, LangId = 1, Code = "Today", Value = "Bugün" },
            new Translate { Id = 317, LangId = 1, Code = "Yesterday", Value = "Dün" },
            new Translate { Id = 319, LangId = 1, Code = "Week", Value = "Hafta" },
            new Translate { Id = 321, LangId = 1, Code = "Month", Value = "Ay" },
            new Translate { Id = 323, LangId = 1, Code = "Year", Value = "Yıl" },
            new Translate { Id = 325, LangId = 1, Code = "Day", Value = "Gün" },
            new Translate { Id = 327, LangId = 1, Code = "Hour", Value = "Saat" },
            new Translate { Id = 329, LangId = 1, Code = "Minute", Value = "Dakika" },
            new Translate { Id = 331, LangId = 1, Code = "Second", Value = "Saniye" },
            new Translate { Id = 333, LangId = 1, Code = "DataTableTitle", Value = "Veri Tablosu" },
            new Translate { Id = 335, LangId = 1, Code = "PdfDownloadTooltip", Value = "PDF İndir" },
            new Translate { Id = 337, LangId = 1, Code = "ExcelDownloadTooltip", Value = "Excel İndir" },
            new Translate { Id = 339, LangId = 1, Code = "CsvDownloadTooltip", Value = "CSV İndir" },
            new Translate { Id = 341, LangId = 1, Code = "ImageDownloadTooltip", Value = "Resim İndir" },
            new Translate { Id = 343, LangId = 1, Code = "TxtDownloadTooltip", Value = "TXT İndir" },
            new Translate { Id = 345, LangId = 1, Code = "JsonDownloadTooltip", Value = "JSON İndir" },
            new Translate { Id = 347, LangId = 1, Code = "XmlDownloadTooltip", Value = "XML İndir" },
            new Translate { Id = 349, LangId = 1, Code = "PdfShareTooltip", Value = "PDF Paylaş" },
            new Translate { Id = 351, LangId = 1, Code = "ExcelShareTooltip", Value = "Excel Paylaş" },
            new Translate { Id = 353, LangId = 1, Code = "CsvShareTooltip", Value = "CSV Paylaş" },
            new Translate { Id = 355, LangId = 1, Code = "ImageShareTooltip", Value = "Resim Paylaş" },
            new Translate { Id = 357, LangId = 1, Code = "TxtShareTooltip", Value = "TXT Paylaş" },
            new Translate { Id = 359, LangId = 1, Code = "JsonShareTooltip", Value = "JSON Paylaş" },
            new Translate { Id = 361, LangId = 1, Code = "XmlShareTooltip", Value = "XML Paylaş" },
            new Translate { Id = 363, LangId = 1, Code = "ShareTitle", Value = "Paylaşım" },
            new Translate { Id = 365, LangId = 1, Code = "NoData", Value = "Veri Yok" },
            new Translate { Id = 367, LangId = 1, Code = "NoConnection", Value = "Bağlantı Yok" },
            new Translate { Id = 369, LangId = 1, Code = "NoDataFound", Value = "Veri Bulunamadı" },
            new Translate { Id = 371, LangId = 1, Code = "Error", Value = "Hata" },
            new Translate { Id = 373, LangId = 1, Code = "Attention", Value = "Dikkat" },
            new Translate { Id = 375, LangId = 1, Code = "Warning", Value = "Uyarı" },
            new Translate { Id = 377, LangId = 1, Code = "Success", Value = "Başarılı" },
            new Translate { Id = 379, LangId = 1, Code = "Information", Value = "Bilgi" },
            new Translate { Id = 381, LangId = 1, Code = "Ok", Value = "Tamam" },
            new Translate { Id = 383, LangId = 1, Code = "Cancel", Value = "İptal" },
            new Translate { Id = 385, LangId = 1, Code = "Yes", Value = "Evet" },
            new Translate { Id = 387, LangId = 1, Code = "No", Value = "Hayır" },
            new Translate { Id = 393, LangId = 1, Code = "ThisActionCannotBeUndone", Value = "Bu işlem geri alınamaz" },
            new Translate { Id = 395, LangId = 1, Code = "NoDataAvailable", Value = "Mevcut veri yok" },
            new Translate { Id = 397, LangId = 1, Code = "VehicleRegistrationNumber", Value = "Araç Kayıt Numarası" },
            new Translate { Id = 399, LangId = 1, Code = "VehicleLicensePlate", Value = "Araç Plakası" },
            new Translate { Id = 401, LangId = 1, Code = "PhoneNumber", Value = "Telefon Numarası" },
            new Translate { Id = 403, LangId = 1, Code = "Search", Value = "Ara" },
            new Translate { Id = 405, LangId = 1, Code = "AdminPanel", Value = "Yönetim Paneli" },
            new Translate { Id = 407, LangId = 1, Code = "GroupInfoHover", Value = "Gruplar burada listelenmektedir." },
            new Translate { Id = 409, LangId = 1, Code = "AtLeastOneSelection", Value = "En Az Bir Seçim Yapılmalıdır" },
            new Translate { Id = 411, LangId = 1, Code = "LanguageInfoHover", Value = "Diller burada listelenmektedir." },
            new Translate { Id = 413, LangId = 1, Code = "LogInfoHover", Value = "Log bilgileri burada listelenmektedir." },
            new Translate { Id = 415, LangId = 1, Code = "OperationClaimInfoHover", Value = "Operasyon yetkileri burada listelenmekteidr." },
            new Translate { Id = 417, LangId = 1, Code = "TranslateInfoHover", Value = "Dil çevirileri burada listelenmektedir." },
            new Translate { Id = 419, LangId = 1, Code = "PasswordsDoNotMatch", Value = "Şifreler eşleşmiyor" },
            new Translate { Id = 421, LangId = 1, Code = "GroupClaims", Value = "Grup Talepleri" },
            new Translate { Id = 423, LangId = 1, Code = "SelectGroupClaim", Value = "Grup Talebi Seçin" },
            new Translate { Id = 429, LangId = 1, Code = "GroupNameHint", Value = "Grup Adı İpucu" },
            new Translate { Id = 431, LangId = 1, Code = "AddGroup", Value = "Grup Ekle" },
            new Translate { Id = 433, LangId = 1, Code = "UpdateGroupClaims", Value = "Grup Taleplerini Güncelle" },
            new Translate { Id = 435, LangId = 1, Code = "UpdateButton", Value = "Güncelle" },
            new Translate { Id = 437, LangId = 1, Code = "UpdateGroup", Value = "Grubu Güncelle" },
            new Translate { Id = 439, LangId = 1, Code = "UpdateGroupUsers", Value = "Grup Kullanıcılarını Güncelle" },
            new Translate { Id = 445, LangId = 1, Code = "AddLanguage", Value = "Dil Ekle" },
            new Translate { Id = 447, LangId = 1, Code = "UpdateLanguage", Value = "Dili Güncelle" },
            new Translate { Id = 451, LangId = 1, Code = "Level", Value = "Seviye" },
            new Translate { Id = 453, LangId = 1, Code = "ExceptionMessage", Value = "İstisna Mesajı" },
            new Translate { Id = 455, LangId = 1, Code = "TimeStamp", Value = "Zaman Damgası" },
            new Translate { Id = 457, LangId = 1, Code = "User", Value = "Kullanıcı" },
            new Translate { Id = 461, LangId = 1, Code = "Type", Value = "Tür" },
            new Translate { Id = 463, LangId = 1, Code = "UpdateOperationClaim", Value = "Operasyon Talebini Güncelle" },
            new Translate { Id = 465, LangId = 1, Code = "AliasHint", Value = "Takma Ad İpucu" },
            new Translate { Id = 621, LangId = 1, Code = "Language", Value = "Dil" },
            new Translate { Id = 625, LangId = 1, Code = "CodeHint", Value = "Kod İpucu" },
            new Translate { Id = 627, LangId = 1, Code = "ValueHint", Value = "Değer İpucu" },
            new Translate { Id = 629, LangId = 1, Code = "AddTranslate", Value = "Çeviri Ekle" },
            new Translate { Id = 631, LangId = 1, Code = "UpdateTranslate", Value = "Çeviriyi Güncelle" },
            new Translate { Id = 633, LangId = 1, Code = "UserClaims", Value = "Kullanıcı Talepleri" },
            new Translate { Id = 635, LangId = 1, Code = "SelectUserClaims", Value = "Kullanıcı Taleplerini Seçin" },
            new Translate { Id = 637, LangId = 1, Code = "SelectUsers", Value = "Kullanıcıları Seçin" },
            new Translate { Id = 641, LangId = 1, Code = "UserGroups", Value = "Kullanıcı Grupları" },
            new Translate { Id = 643, LangId = 1, Code = "SelectUserGroups", Value = "Kullanıcı Gruplarını Seçin" },
            new Translate { Id = 645, LangId = 1, Code = "AddUser", Value = "Kullanıcı Ekle" },
            new Translate { Id = 649, LangId = 1, Code = "FullNameHint", Value = "Tam Ad İpucu" },
            new Translate { Id = 653, LangId = 1, Code = "AddressHint", Value = "Adres İpucu" },
            new Translate { Id = 655, LangId = 1, Code = "Active", Value = "Aktif" },
            new Translate { Id = 657, LangId = 1, Code = "Inactive", Value = "Pasif" },
            new Translate { Id = 661, LangId = 1, Code = "NotesHint", Value = "Notlar İpucu" },
            new Translate { Id = 669, LangId = 1, Code = "UpdateUserClaims", Value = "Kullanıcı Taleplerini Güncelle" },
            new Translate { Id = 671, LangId = 1, Code = "UpdateUserGroups", Value = "Kullanıcı Gruplarını Güncelle" },
            new Translate { Id = 673, LangId = 1, Code = "UpdateUsers", Value = "Kullanıcıları Güncelle" },
            new Translate { Id = 687, LangId = 1, Code = "Edit", Value = "Düzenle" },
            new Translate { Id = 697, LangId = 1, Code = "OK", Value = "Tamam" },
            new Translate { Id = 699, LangId = 1, Code = "Back", Value = "Geri" },
            new Translate { Id = 701, LangId = 1, Code = "Next", Value = "İleri" },
            new Translate { Id = 707, LangId = 1, Code = "Filter", Value = "Filtrele" },
            new Translate { Id = 709, LangId = 1, Code = "Clear", Value = "Temizle" },
            new Translate { Id = 711, LangId = 1, Code = "Sort", Value = "Sırala" },
            new Translate { Id = 713, LangId = 1, Code = "Ascending", Value = "Artan" },
            new Translate { Id = 715, LangId = 1, Code = "Descending", Value = "Azalan" },
            new Translate { Id = 719, LangId = 1, Code = "ReturnHome", Value = "Anasayfaya dön" },
            new Translate { Id = 721, LangId = 1, Code = "Welcome", Value = "Hoşgeldiniz" },
            new Translate { Id = 723, LangId = 1, Code = "LogIn", Value = "Giriş Yap" },
            new Translate { Id = 725, LangId = 1, Code = "LogOut", Value = "Çıkış Yap" },
            new Translate { Id = 727, LangId = 1, Code = "Register", Value = "Kayıt Ol" },
            new Translate { Id = 735, LangId = 1, Code = "Username", Value = "Kullanıcı Adı" },
            new Translate { Id = 737, LangId = 1, Code = "ForgotPassword", Value = "Şifremi Unuttum" },
            new Translate { Id = 739, LangId = 1, Code = "RememberMe", Value = "Beni Hatırla" },
            new Translate { Id = 741, LangId = 1, Code = "Submit", Value = "Gönder" },
            new Translate { Id = 743, LangId = 1, Code = "Reset", Value = "Sıfırla" },
            new Translate { Id = 745, LangId = 1, Code = "Retry", Value = "Yeniden Dene" },
            new Translate { Id = 755, LangId = 1, Code = "Confirm", Value = "Onayla" },
            new Translate { Id = 757, LangId = 1, Code = "Exit", Value = "Çıkış" },
            new Translate { Id = 759, LangId = 1, Code = "Close", Value = "Kapat" },
            new Translate { Id = 761, LangId = 1, Code = "Open", Value = "Aç" },
            new Translate { Id = 763, LangId = 1, Code = "Settings", Value = "Ayarlar" },
            new Translate { Id = 765, LangId = 1, Code = "Help", Value = "Yardım" },
            new Translate { Id = 767, LangId = 1, Code = "About", Value = "Hakkında" },
            new Translate { Id = 769, LangId = 1, Code = "SubscriptionPageTitle", Value = "Abonelik Yönetimi" },
            new Translate { Id = 771, LangId = 1, Code = "AdminPanelPageInvoiceTitle", Value = "Faturalar" },
            new Translate { Id = 773, LangId = 1, Code = "AdminPanelPageContractTitle", Value = "Sözleşmeler" },
            new Translate { Id = 775, LangId = 1, Code = "AdminPanelPageOrderTitle", Value = "Siparişler" },
            new Translate { Id = 777, LangId = 1, Code = "AdminPanelPageCompaniesDocTitle", Value = "Şirket Dökümanları" },
            new Translate { Id = 779, LangId = 1, Code = "AdminPanelOurServicesTitle", Value = "Hizmetlerimiz" },
            new Translate { Id = 781, LangId = 1, Code = "AdminPanelCuponCodesTitle", Value = "Kupon Kodları" },
            new Translate { Id = 11, LangId = 2, Code = "Login", Value = "Login" },
            new Translate { Id = 12, LangId = 2, Code = "Email", Value = "Email" },
            new Translate { Id = 13, LangId = 2, Code = "Password", Value = "Password" },
            new Translate { Id = 14, LangId = 2, Code = "Update", Value = "Update" },
            new Translate { Id = 15, LangId = 2, Code = "Delete", Value = "Delete" },
            new Translate { Id = 16, LangId = 2, Code = "UsersGroups", Value = "User's Groups" },
            new Translate { Id = 17, LangId = 2, Code = "UsersClaims", Value = "User's Claims" },
            new Translate { Id = 18, LangId = 2, Code = "Create", Value = "Create" },
            new Translate { Id = 19, LangId = 2, Code = "Users", Value = "Users" },
            new Translate { Id = 20, LangId = 2, Code = "Groups", Value = "Groups" },
            new Translate { Id = 22, LangId = 2, Code = "OperationClaim", Value = "Operation Claim" },
            new Translate { Id = 24, LangId = 2, Code = "Languages", Value = "Languages" },
            new Translate { Id = 26, LangId = 2, Code = "TranslateWords", Value = "Translate Words" },
            new Translate { Id = 28, LangId = 2, Code = "Management", Value = "Management" },
            new Translate { Id = 30, LangId = 2, Code = "AppMenu", Value = "Application" },
            new Translate { Id = 32, LangId = 2, Code = "Added", Value = "Successfully Added." },
            new Translate { Id = 34, LangId = 2, Code = "Updated", Value = "Successfully Updated." },
            new Translate { Id = 36, LangId = 2, Code = "Deleted", Value = "Successfully Deleted." },
            new Translate { Id = 44, LangId = 2, Code = "VerifyCid", Value = "Verify Citizen Id" },
            new Translate { Id = 60, LangId = 2, Code = "CID", Value = "Citizenship Number" },
            new Translate { Id = 62, LangId = 2, Code = "PasswordEmpty", Value = "Password can not be empty!" },
            new Translate { Id = 76, LangId = 2, Code = "InvalidCode", Value = "You Entered An Invalid Code!" },
            new Translate { Id = 84, LangId = 2, Code = "Unknown", Value = "Unknown!" },
            new Translate { Id = 86, LangId = 2, Code = "NewPassword", Value = "New Password:" },
            new Translate { Id = 88, LangId = 2, Code = "ChangePassword", Value = "Change Password" },
            new Translate { Id = 90, LangId = 2, Code = "Save", Value = "Save" },
            new Translate { Id = 92, LangId = 2, Code = "GroupName", Value = "Group Name" },
            new Translate { Id = 94, LangId = 2, Code = "FullName", Value = "Full Name" },
            new Translate { Id = 96, LangId = 2, Code = "Address", Value = "Address" },
            new Translate { Id = 98, LangId = 2, Code = "Notes", Value = "Notes" },
            new Translate { Id = 100, LangId = 2, Code = "ConfirmPassword", Value = "Confirm Password" },
            new Translate { Id = 102, LangId = 2, Code = "Code", Value = "Code" },
            new Translate { Id = 104, LangId = 2, Code = "Alias", Value = "Alias" },
            new Translate { Id = 106, LangId = 2, Code = "Description", Value = "Description" },
            new Translate { Id = 108, LangId = 2, Code = "Value", Value = "Value" },
            new Translate { Id = 110, LangId = 2, Code = "LangCode", Value = "Lang Code" },
            new Translate { Id = 112, LangId = 2, Code = "Name", Value = "Name" },
            new Translate { Id = 114, LangId = 2, Code = "MobilePhones", Value = "Mobile Phone" },
            new Translate { Id = 116, LangId = 2, Code = "NoRecordsFound", Value = "No Records Found" },
            new Translate { Id = 118, LangId = 2, Code = "Required", Value = "This field is required!" },
            new Translate { Id = 120, LangId = 2, Code = "Permissions", Value = "İzinler" },
            new Translate { Id = 122, LangId = 2, Code = "GroupList", Value = "Group List" },
            new Translate { Id = 124, LangId = 2, Code = "GrupPermissions", Value = "Grup Permissions" },
            new Translate { Id = 126, LangId = 2, Code = "Add", Value = "Add" },
            new Translate { Id = 128, LangId = 2, Code = "UserList", Value = "User List" },
            new Translate { Id = 130, LangId = 2, Code = "OperationClaimList", Value = "OperationClaim List" },
            new Translate { Id = 132, LangId = 2, Code = "LanguageList", Value = "Language List" },
            new Translate { Id = 134, LangId = 2, Code = "TranslateList", Value = "Translate List" },
            new Translate { Id = 136, LangId = 2, Code = "LogList", Value = "LogList" },
            new Translate { Id = 138, LangId = 2, Code = "DeleteConfirm", Value = "Are you sure?" },
            new Translate { Id = 140, LangId = 2, Code = "AppName", Value = "Flutter DevArchitecture" },
            new Translate { Id = 178, LangId = 2, Code = "OperationClaimExists", Value = "This operation permit already exists." },
            new Translate { Id = 180, LangId = 2, Code = "StringLengthMustBeGreaterThanThree", Value = "Please Enter A Phrase Of At Least 3 Characters." },
            new Translate { Id = 182, LangId = 2, Code = "CouldNotBeVerifyCid", Value = "Could not be verify Citizen Id" },
            new Translate { Id = 186, LangId = 2, Code = "AuthorizationsDenied", Value = "It has been detected that you are trying to enter an area that you do not have authorization." },
            new Translate { Id = 188, LangId = 2, Code = "UserNotFound", Value = "Credentials Could Not Verify. Please use the New Registration Screen." },
            new Translate { Id = 190, LangId = 2, Code = "PasswordError", Value = "Credentials Failed to Authenticate, Username and / or password incorrect." },
            new Translate { Id = 192, LangId = 2, Code = "SuccessfulLogin", Value = "Login to the system is successful." },
            new Translate { Id = 194, LangId = 2, Code = "SendMobileCode", Value = "Please Enter The Code Sent To You By SMS!" },
            new Translate { Id = 196, LangId = 2, Code = "NameAlreadyExist", Value = "The Object You Are Trying To Create Already Exists." },
            new Translate { Id = 198, LangId = 2, Code = "WrongCitizenId", Value = "Citizenship Number Not Found In Our System. Please Create New Registration!" },
            new Translate { Id = 200, LangId = 2, Code = "CitizenNumber", Value = "Citizenship Number" },
            new Translate { Id = 204, LangId = 2, Code = "PasswordLength", Value = "Must be at least 8 characters long!" },
            new Translate { Id = 206, LangId = 2, Code = "PasswordUppercaseLetter", Value = "Must Contain At Least 1 Capital Letter!" },
            new Translate { Id = 208, LangId = 2, Code = "PasswordLowercaseLetter", Value = "Must Contain At Least 1 Lowercase Letter!" },
            new Translate { Id = 210, LangId = 2, Code = "PasswordDigit", Value = "It Must Contain At Least 1 Digit!" },
            new Translate { Id = 212, LangId = 2, Code = "PasswordSpecialCharacter", Value = "Must Contain At Least 1 Symbol!" },
            new Translate { Id = 214, LangId = 2, Code = "SendPassword", Value = "Your new password has been sent to your e-mail address." },
            new Translate { Id = 218, LangId = 2, Code = "SmsServiceNotFound", Value = "Unable to Reach SMS Service." },
            new Translate { Id = 220, LangId = 2, Code = "TrueButCellPhone", Value = "The information is correct. Cell phone is required." },
            new Translate { Id = 222, LangId = 2, Code = "TokenProviderException", Value = "Token Provider cannot be empty!" },
            new Translate { Id = 278, LangId = 2, Code = "CantBeEmpty", Value = "can not be empty!" },
            new Translate { Id = 280, LangId = 2, Code = "InvalidEmail", Value = "Please enter a valid email address!" },
            new Translate { Id = 282, LangId = 2, Code = "InvalidPassword", Value = "Please enter a valid password address!" },
            new Translate { Id = 284, LangId = 2, Code = "Status", Value = "Status" },
            new Translate { Id = 286, LangId = 2, Code = "UpdateUser", Value = "Update User" },
            new Translate { Id = 288, LangId = 2, Code = "PageNotFound", Value = "Page Not Found!" },
            new Translate { Id = 290, LangId = 2, Code = "Loading", Value = "Loading" },
            new Translate { Id = 292, LangId = 2, Code = "HomePage", Value = "Home Page" },
            new Translate { Id = 294, LangId = 2, Code = "ReturnHomePage", Value = "Return Home Page" },
            new Translate { Id = 296, LangId = 2, Code = "Categories", Value = "Categories" },
            new Translate { Id = 298, LangId = 2, Code = "Sells", Value = "Sells" },
            new Translate { Id = 300, LangId = 2, Code = "Days", Value = "Days" },
            new Translate { Id = 302, LangId = 2, Code = "Sales", Value = "Sales" },
            new Translate { Id = 306, LangId = 2, Code = "Months", Value = "Months" },
            new Translate { Id = 308, LangId = 2, Code = "Years", Value = "Years" },
            new Translate { Id = 310, LangId = 2, Code = "Hours", Value = "Hours" },
            new Translate { Id = 312, LangId = 2, Code = "Minutes", Value = "Minutes" },
            new Translate { Id = 314, LangId = 2, Code = "Seconds", Value = "Seconds" },
            new Translate { Id = 316, LangId = 2, Code = "Today", Value = "Today" },
            new Translate { Id = 318, LangId = 2, Code = "Yesterday", Value = "Yesterday" },
            new Translate { Id = 320, LangId = 2, Code = "Week", Value = "Week" },
            new Translate { Id = 322, LangId = 2, Code = "Month", Value = "Month" },
            new Translate { Id = 324, LangId = 2, Code = "Year", Value = "Year" },
            new Translate { Id = 326, LangId = 2, Code = "Day", Value = "Day" },
            new Translate { Id = 328, LangId = 2, Code = "Hour", Value = "Hour" },
            new Translate { Id = 330, LangId = 2, Code = "Minute", Value = "Minute" },
            new Translate { Id = 332, LangId = 2, Code = "Second", Value = "Second" },
            new Translate { Id = 334, LangId = 2, Code = "DataTableTitle", Value = "Data Table Title" },
            new Translate { Id = 336, LangId = 2, Code = "PdfDownloadTooltip", Value = "Download PDF" },
            new Translate { Id = 338, LangId = 2, Code = "ExcelDownloadTooltip", Value = "Download Excel" },
            new Translate { Id = 340, LangId = 2, Code = "CsvDownloadTooltip", Value = "Download CSV" },
            new Translate { Id = 342, LangId = 2, Code = "ImageDownloadTooltip", Value = "Download Image" },
            new Translate { Id = 344, LangId = 2, Code = "TxtDownloadTooltip", Value = "Download TXT" },
            new Translate { Id = 346, LangId = 2, Code = "JsonDownloadTooltip", Value = "Download JSON" },
            new Translate { Id = 348, LangId = 2, Code = "XmlDownloadTooltip", Value = "Download XML" },
            new Translate { Id = 350, LangId = 2, Code = "PdfShareTooltip", Value = "Share PDF" },
            new Translate { Id = 352, LangId = 2, Code = "ExcelShareTooltip", Value = "Share Excel" },
            new Translate { Id = 354, LangId = 2, Code = "CsvShareTooltip", Value = "Share CSV" },
            new Translate { Id = 356, LangId = 2, Code = "ImageShareTooltip", Value = "Share Image" },
            new Translate { Id = 358, LangId = 2, Code = "TxtShareTooltip", Value = "Share TXT" },
            new Translate { Id = 360, LangId = 2, Code = "JsonShareTooltip", Value = "Share JSON" },
            new Translate { Id = 362, LangId = 2, Code = "XmlShareTooltip", Value = "Share XML" },
            new Translate { Id = 364, LangId = 2, Code = "ShareTitle", Value = "Share Title" },
            new Translate { Id = 366, LangId = 2, Code = "NoData", Value = "No Data" },
            new Translate { Id = 368, LangId = 2, Code = "NoConnection", Value = "No Connection" },
            new Translate { Id = 370, LangId = 2, Code = "NoDataFound", Value = "No Data Found" },
            new Translate { Id = 372, LangId = 2, Code = "Error", Value = "Error" },
            new Translate { Id = 374, LangId = 2, Code = "Attention", Value = "Attention" },
            new Translate { Id = 376, LangId = 2, Code = "Warning", Value = "Warning" },
            new Translate { Id = 378, LangId = 2, Code = "Success", Value = "Success" },
            new Translate { Id = 380, LangId = 2, Code = "Information", Value = "Information" },
            new Translate { Id = 382, LangId = 2, Code = "Ok", Value = "Ok" },
            new Translate { Id = 384, LangId = 2, Code = "Cancel", Value = "Cancel" },
            new Translate { Id = 386, LangId = 2, Code = "Yes", Value = "Yes" },
            new Translate { Id = 388, LangId = 2, Code = "No", Value = "No" },
            new Translate { Id = 394, LangId = 2, Code = "ThisActionCannotBeUndone", Value = "This action cannot be undone" },
            new Translate { Id = 396, LangId = 2, Code = "NoDataAvailable", Value = "No Data Available" },
            new Translate { Id = 398, LangId = 2, Code = "VehicleRegistrationNumber", Value = "Vehicle Registration Number" },
            new Translate { Id = 400, LangId = 2, Code = "VehicleLicensePlate", Value = "Vehicle License Plate" },
            new Translate { Id = 402, LangId = 2, Code = "PhoneNumber", Value = "Phone Number" },
            new Translate { Id = 404, LangId = 2, Code = "Search", Value = "Search" },
            new Translate { Id = 406, LangId = 2, Code = "AdminPanel", Value = "Admin Panel" },
            new Translate { Id = 408, LangId = 2, Code = "GroupInfoHover", Value = "The group is listed." },
            new Translate { Id = 410, LangId = 2, Code = "AtLeastOneSelection", Value = "At Least One Selection Is Required" },
            new Translate { Id = 412, LangId = 2, Code = "LanguageInfoHover", Value = "The languages are listed." },
            new Translate { Id = 414, LangId = 2, Code = "LogInfoHover", Value = "Log information is listed." },
            new Translate { Id = 416, LangId = 2, Code = "OperationClaimInfoHover", Value = "Operation claims are listed." },
            new Translate { Id = 418, LangId = 2, Code = "TranslateInfoHover", Value = "The language translations are listed." },
            new Translate { Id = 420, LangId = 2, Code = "PasswordsDoNotMatch", Value = "Passwords do not match" },
            new Translate { Id = 422, LangId = 2, Code = "GroupClaims", Value = "Group Claims" },
            new Translate { Id = 424, LangId = 2, Code = "SelectGroupClaim", Value = "Select Group Claim" },
            new Translate { Id = 430, LangId = 2, Code = "GroupNameHint", Value = "Group Name Hint" },
            new Translate { Id = 432, LangId = 2, Code = "AddGroup", Value = "Add Group" },
            new Translate { Id = 434, LangId = 2, Code = "UpdateGroupClaims", Value = "Update Group Claims" },
            new Translate { Id = 436, LangId = 2, Code = "UpdateButton", Value = "Update" },
            new Translate { Id = 438, LangId = 2, Code = "UpdateGroup", Value = "Update Group" },
            new Translate { Id = 440, LangId = 2, Code = "UpdateGroupUsers", Value = "Update Group Users" },
            new Translate { Id = 446, LangId = 2, Code = "AddLanguage", Value = "Add Language" },
            new Translate { Id = 448, LangId = 2, Code = "UpdateLanguage", Value = "Update Language" },
            new Translate { Id = 452, LangId = 2, Code = "Level", Value = "Level" },
            new Translate { Id = 454, LangId = 2, Code = "ExceptionMessage", Value = "Exception Message" },
            new Translate { Id = 456, LangId = 2, Code = "TimeStamp", Value = "Time Stamp" },
            new Translate { Id = 458, LangId = 2, Code = "User", Value = "User" },
            new Translate { Id = 462, LangId = 2, Code = "Type", Value = "Type" },
            new Translate { Id = 464, LangId = 2, Code = "UpdateOperationClaim", Value = "Update Operation Claim" },
            new Translate { Id = 466, LangId = 2, Code = "AliasHint", Value = "Alias Hint" },
            new Translate { Id = 622, LangId = 2, Code = "Language", Value = "Language" },
            new Translate { Id = 626, LangId = 2, Code = "CodeHint", Value = "Code Hint" },
            new Translate { Id = 628, LangId = 2, Code = "ValueHint", Value = "Value Hint" },
            new Translate { Id = 630, LangId = 2, Code = "AddTranslate", Value = "Add Translate" },
            new Translate { Id = 632, LangId = 2, Code = "UpdateTranslate", Value = "Update Translate" },
            new Translate { Id = 634, LangId = 2, Code = "UserClaims", Value = "User Claims" },
            new Translate { Id = 636, LangId = 2, Code = "SelectUserClaims", Value = "Select User Claims" },
            new Translate { Id = 638, LangId = 2, Code = "SelectUsers", Value = "Select Users" },
            new Translate { Id = 642, LangId = 2, Code = "UserGroups", Value = "User Groups" },
            new Translate { Id = 644, LangId = 2, Code = "SelectUserGroups", Value = "Select User Groups" },
            new Translate { Id = 646, LangId = 2, Code = "AddUser", Value = "Add User" },
            new Translate { Id = 650, LangId = 2, Code = "FullNameHint", Value = "Full Name Hint" },
            new Translate { Id = 654, LangId = 2, Code = "AddressHint", Value = "Address Hint" },
            new Translate { Id = 656, LangId = 2, Code = "Active", Value = "Active" },
            new Translate { Id = 658, LangId = 2, Code = "Inactive", Value = "Inactive" },
            new Translate { Id = 662, LangId = 2, Code = "NotesHint", Value = "Notes Hint" },
            new Translate { Id = 670, LangId = 2, Code = "UpdateUserClaims", Value = "Update User Claims" },
            new Translate { Id = 672, LangId = 2, Code = "UpdateUserGroups", Value = "Update User Groups" },
            new Translate { Id = 674, LangId = 2, Code = "UpdateUsers", Value = "Update Users" },
            new Translate { Id = 688, LangId = 2, Code = "Edit", Value = "Edit" },
            new Translate { Id = 698, LangId = 2, Code = "OK", Value = "OK" },
            new Translate { Id = 700, LangId = 2, Code = "Back", Value = "Back" },
            new Translate { Id = 702, LangId = 2, Code = "Next", Value = "Next" },
            new Translate { Id = 708, LangId = 2, Code = "Filter", Value = "Filter" },
            new Translate { Id = 710, LangId = 2, Code = "Clear", Value = "Clear" },
            new Translate { Id = 712, LangId = 2, Code = "Sort", Value = "Sort" },
            new Translate { Id = 714, LangId = 2, Code = "Ascending", Value = "Ascending" },
            new Translate { Id = 716, LangId = 2, Code = "Descending", Value = "Descending" },
            new Translate { Id = 720, LangId = 2, Code = "ReturnHome", Value = "Return Home" },
            new Translate { Id = 722, LangId = 2, Code = "Welcome", Value = "Welcome" },
            new Translate { Id = 724, LangId = 2, Code = "LogIn", Value = "Log In" },
            new Translate { Id = 726, LangId = 2, Code = "LogOut", Value = "Log Out" },
            new Translate { Id = 728, LangId = 2, Code = "Register", Value = "Register" },
            new Translate { Id = 736, LangId = 2, Code = "Username", Value = "Username" },
            new Translate { Id = 738, LangId = 2, Code = "ForgotPassword", Value = "Forgot Password" },
            new Translate { Id = 740, LangId = 2, Code = "RememberMe", Value = "Remember Me" },
            new Translate { Id = 742, LangId = 2, Code = "Submit", Value = "Submit" },
            new Translate { Id = 744, LangId = 2, Code = "Reset", Value = "Reset" },
            new Translate { Id = 746, LangId = 2, Code = "Retry", Value = "Retry" },
            new Translate { Id = 756, LangId = 2, Code = "Confirm", Value = "Confirm" },
            new Translate { Id = 758, LangId = 2, Code = "Exit", Value = "Exit" },
            new Translate { Id = 760, LangId = 2, Code = "Close", Value = "Close" },
            new Translate { Id = 762, LangId = 2, Code = "Open", Value = "Open" },
            new Translate { Id = 764, LangId = 2, Code = "Settings", Value = "Settings" },
            new Translate { Id = 766, LangId = 2, Code = "Help", Value = "Help" },
            new Translate { Id = 768, LangId = 2, Code = "About", Value = "About" },
            new Translate { Id = 770, LangId = 2, Code = "SubscriptionPageTitle", Value = "Subscription Management" },
            new Translate { Id = 772, LangId = 2, Code = "AdminPanelPageInvoiceTitle", Value = "Invoices" },
            new Translate { Id = 774, LangId = 2, Code = "AdminPanelPageContractTitle", Value = "Contracts" },
            new Translate { Id = 776, LangId = 2, Code = "AdminPanelPageOrderTitle", Value = "Orders" },
            new Translate { Id = 778, LangId = 2, Code = "AdminPanelPageCompaniesDocTitle", Value = "Companies Docs" },
            new Translate { Id = 780, LangId = 2, Code = "AdminPanelOurServicesTitle", Value = "Our Services" },
            new Translate { Id = 782, LangId = 2, Code = "AdminPanelCuponCodesTitle", Value = "Cupon Codes" },
            };
        }
    }
}