services:
  api_product_management_blue_dev:
    hostname: api_product_management_blue_dev
    container_name: api_product_management_blue_dev
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    environment:
      ASPNETCORE_ENVIRONMENT: 'Staging'
    labels:
          - "traefik.enable=false"
    networks:
      - log-net
      - traefik-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  product_management_blue_dev:
    hostname: product_management_blue_dev
    container_name: product_management_blue_dev
    build:
      context: ./UiPreparation/UI # Path to the build folder
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - "traefik.enable=false"
    networks:
      - log-net
      - traefik-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/#/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy: 
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  log-net:
    external: true
    name: log-net
  traefik-net:
    external: true
    name: traefik-net