// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations.Pg
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20251006081154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.MobileLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSend")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId", "Provider");

                    b.ToTable("MobileLogins");
                });

            modelBuilder.Entity("Entities.Concrete.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorName")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Entities.Concrete.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Entities.Concrete.GroupClaim", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<int?>("OperationClaimId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "ClaimId");

                    b.HasIndex("OperationClaimId");

                    b.ToTable("GroupClaims");
                });

            modelBuilder.Entity("Entities.Concrete.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "tr-TR",
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en-US",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Entities.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Entities.Concrete.Translate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LangId")
                        .HasColumnType("integer");

                    b.Property<int?>("LanguagesId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("LanguagesId");

                    b.ToTable("Translates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Welcome",
                            LangId = 1,
                            Value = "Hoş geldiniz"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ProductManagement",
                            LangId = 1,
                            Value = "Ürün Yönetimi"
                        },
                        new
                        {
                            Id = 3,
                            Code = "CloseSidebar",
                            LangId = 1,
                            Value = "Menüyü Kapat"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ADMIN",
                            LangId = 1,
                            Value = "YÖNETİM"
                        },
                        new
                        {
                            Id = 5,
                            Code = "APP",
                            LangId = 1,
                            Value = "UYGULAMA"
                        },
                        new
                        {
                            Id = 6,
                            Code = "Profile",
                            LangId = 1,
                            Value = "Profil"
                        },
                        new
                        {
                            Id = 7,
                            Code = "Logout",
                            LangId = 1,
                            Value = "Çıkış"
                        },
                        new
                        {
                            Id = 8,
                            Code = "OpenSidebar",
                            LangId = 1,
                            Value = "Menüyü Aç"
                        },
                        new
                        {
                            Id = 9,
                            Code = "Logo",
                            LangId = 1,
                            Value = "Logo"
                        },
                        new
                        {
                            Id = 10,
                            Code = "Welcome",
                            LangId = 2,
                            Value = "Welcome"
                        },
                        new
                        {
                            Id = 11,
                            Code = "ProductManagement",
                            LangId = 2,
                            Value = "Product Management"
                        },
                        new
                        {
                            Id = 12,
                            Code = "CloseSidebar",
                            LangId = 2,
                            Value = "Close Sidebar"
                        },
                        new
                        {
                            Id = 13,
                            Code = "ADMIN",
                            LangId = 2,
                            Value = "ADMIN"
                        },
                        new
                        {
                            Id = 14,
                            Code = "APP",
                            LangId = 2,
                            Value = "APP"
                        },
                        new
                        {
                            Id = 15,
                            Code = "Profile",
                            LangId = 2,
                            Value = "Profile"
                        },
                        new
                        {
                            Id = 16,
                            Code = "Logout",
                            LangId = 2,
                            Value = "Logout"
                        },
                        new
                        {
                            Id = 17,
                            Code = "OpenSidebar",
                            LangId = 2,
                            Value = "Open Sidebar"
                        },
                        new
                        {
                            Id = 18,
                            Code = "Logo",
                            LangId = 2,
                            Value = "Logo"
                        },
                        new
                        {
                            Id = 19,
                            Code = "Login",
                            LangId = 1,
                            Value = "Giriş"
                        },
                        new
                        {
                            Id = 20,
                            Code = "ProductManagement",
                            LangId = 1,
                            Value = "Ürün Yönetimi"
                        },
                        new
                        {
                            Id = 21,
                            Code = "Email",
                            LangId = 1,
                            Value = "E-posta"
                        },
                        new
                        {
                            Id = 22,
                            Code = "PleaseEnterValidEmail",
                            LangId = 1,
                            Value = "Lütfen geçerli bir e-posta adresi girin"
                        },
                        new
                        {
                            Id = 23,
                            Code = "Password",
                            LangId = 1,
                            Value = "Şifre"
                        },
                        new
                        {
                            Id = 24,
                            Code = "PleaseEnterYourPassword",
                            LangId = 1,
                            Value = "Lütfen şifrenizi girin"
                        },
                        new
                        {
                            Id = 25,
                            Code = "SelectLanguage",
                            LangId = 1,
                            Value = "Dil Seçin"
                        },
                        new
                        {
                            Id = 26,
                            Code = "PleaseSelect",
                            LangId = 1,
                            Value = "Lütfen Seçin"
                        },
                        new
                        {
                            Id = 27,
                            Code = "DontHaveAnAccountRegister",
                            LangId = 1,
                            Value = "Hesabınız yok mu? Kayıt olun"
                        },
                        new
                        {
                            Id = 28,
                            Code = "Login",
                            LangId = 2,
                            Value = "Login"
                        },
                        new
                        {
                            Id = 29,
                            Code = "ProductManagement",
                            LangId = 2,
                            Value = "Product Management"
                        },
                        new
                        {
                            Id = 30,
                            Code = "Email",
                            LangId = 2,
                            Value = "Email"
                        },
                        new
                        {
                            Id = 31,
                            Code = "PleaseEnterValidEmail",
                            LangId = 2,
                            Value = "Please enter a valid email address"
                        },
                        new
                        {
                            Id = 32,
                            Code = "Password",
                            LangId = 2,
                            Value = "Password"
                        },
                        new
                        {
                            Id = 33,
                            Code = "PleaseEnterYourPassword",
                            LangId = 2,
                            Value = "Please enter your password"
                        },
                        new
                        {
                            Id = 34,
                            Code = "SelectLanguage",
                            LangId = 2,
                            Value = "Select Language"
                        },
                        new
                        {
                            Id = 35,
                            Code = "PleaseSelect",
                            LangId = 2,
                            Value = "Please Select"
                        },
                        new
                        {
                            Id = 36,
                            Code = "DontHaveAnAccountRegister",
                            LangId = 2,
                            Value = "Don't have an account? Register"
                        },
                        new
                        {
                            Id = 37,
                            Code = "Register",
                            LangId = 1,
                            Value = "Kayıt Ol"
                        },
                        new
                        {
                            Id = 38,
                            Code = "ProductManagement",
                            LangId = 1,
                            Value = "Ürün Yönetimi"
                        },
                        new
                        {
                            Id = 39,
                            Code = "Username",
                            LangId = 1,
                            Value = "Kullanıcı Adı"
                        },
                        new
                        {
                            Id = 40,
                            Code = "PleaseEnterUsername",
                            LangId = 1,
                            Value = "Lütfen kullanıcı adınızı girin"
                        },
                        new
                        {
                            Id = 41,
                            Code = "Email",
                            LangId = 1,
                            Value = "E-posta"
                        },
                        new
                        {
                            Id = 42,
                            Code = "PleaseEnterValidEmail",
                            LangId = 1,
                            Value = "Lütfen geçerli bir e-posta adresi girin"
                        },
                        new
                        {
                            Id = 43,
                            Code = "Password",
                            LangId = 1,
                            Value = "Şifre"
                        },
                        new
                        {
                            Id = 44,
                            Code = "PleaseEnterPassword",
                            LangId = 1,
                            Value = "Lütfen şifrenizi girin"
                        },
                        new
                        {
                            Id = 45,
                            Code = "ConfirmPassword",
                            LangId = 1,
                            Value = "Şifreyi Onayla"
                        },
                        new
                        {
                            Id = 46,
                            Code = "PasswordsDoNotMatchOrEmpty",
                            LangId = 1,
                            Value = "Şifreler uyuşmuyor veya boş bıraktınız"
                        },
                        new
                        {
                            Id = 47,
                            Code = "SelectLanguage",
                            LangId = 1,
                            Value = "Dil Seçin"
                        },
                        new
                        {
                            Id = 48,
                            Code = "PleaseSelect",
                            LangId = 1,
                            Value = "Lütfen Seçin"
                        },
                        new
                        {
                            Id = 49,
                            Code = "AlreadyHaveAnAccountLogin",
                            LangId = 1,
                            Value = "Zaten hesabınız var mı? Giriş yapın"
                        },
                        new
                        {
                            Id = 50,
                            Code = "Register",
                            LangId = 2,
                            Value = "Register"
                        },
                        new
                        {
                            Id = 51,
                            Code = "ProductManagement",
                            LangId = 2,
                            Value = "Product Management"
                        },
                        new
                        {
                            Id = 52,
                            Code = "Username",
                            LangId = 2,
                            Value = "Username"
                        },
                        new
                        {
                            Id = 53,
                            Code = "PleaseEnterUsername",
                            LangId = 2,
                            Value = "Please enter your username"
                        },
                        new
                        {
                            Id = 54,
                            Code = "Email",
                            LangId = 2,
                            Value = "Email"
                        },
                        new
                        {
                            Id = 55,
                            Code = "PleaseEnterValidEmail",
                            LangId = 2,
                            Value = "Please enter a valid email address"
                        },
                        new
                        {
                            Id = 56,
                            Code = "Password",
                            LangId = 2,
                            Value = "Password"
                        },
                        new
                        {
                            Id = 57,
                            Code = "PleaseEnterPassword",
                            LangId = 2,
                            Value = "Please enter your password"
                        },
                        new
                        {
                            Id = 58,
                            Code = "ConfirmPassword",
                            LangId = 2,
                            Value = "Confirm Password"
                        },
                        new
                        {
                            Id = 59,
                            Code = "PasswordsDoNotMatchOrEmpty",
                            LangId = 2,
                            Value = "Passwords do not match or are empty"
                        },
                        new
                        {
                            Id = 60,
                            Code = "SelectLanguage",
                            LangId = 2,
                            Value = "Select Language"
                        },
                        new
                        {
                            Id = 61,
                            Code = "PleaseSelect",
                            LangId = 2,
                            Value = "Please Select"
                        },
                        new
                        {
                            Id = 62,
                            Code = "AlreadyHaveAnAccountLogin",
                            LangId = 2,
                            Value = "Already have an account? Login"
                        },
                        new
                        {
                            Id = 63,
                            Code = "PRODUCT.ADD.TITLE",
                            LangId = 1,
                            Value = "Yeni Ürün Ekle"
                        },
                        new
                        {
                            Id = 64,
                            Code = "PRODUCT.NAME",
                            LangId = 1,
                            Value = "Ürün Adı"
                        },
                        new
                        {
                            Id = 65,
                            Code = "PRODUCT.PRICE",
                            LangId = 1,
                            Value = "Fiyat"
                        },
                        new
                        {
                            Id = 66,
                            Code = "PRODUCT.STOCK",
                            LangId = 1,
                            Value = "Stok"
                        },
                        new
                        {
                            Id = 67,
                            Code = "PRODUCT.COLORS",
                            LangId = 1,
                            Value = "Renkler"
                        },
                        new
                        {
                            Id = 68,
                            Code = "PRODUCT.COLOR_NAME",
                            LangId = 1,
                            Value = "Renk Adı"
                        },
                        new
                        {
                            Id = 69,
                            Code = "PRODUCT.ADD_COLOR",
                            LangId = 1,
                            Value = "Renk Ekle"
                        },
                        new
                        {
                            Id = 70,
                            Code = "VALIDATION.NAME_REQUIRED",
                            LangId = 1,
                            Value = "Ürün adı zorunludur"
                        },
                        new
                        {
                            Id = 71,
                            Code = "VALIDATION.PRICE_INVALID",
                            LangId = 1,
                            Value = "Lütfen geçerli bir fiyat girin"
                        },
                        new
                        {
                            Id = 72,
                            Code = "VALIDATION.STOCK_INVALID",
                            LangId = 1,
                            Value = "Lütfen geçerli bir stok miktarı girin"
                        },
                        new
                        {
                            Id = 73,
                            Code = "GENERAL.SAVE",
                            LangId = 1,
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = 74,
                            Code = "GENERAL.CANCEL",
                            LangId = 1,
                            Value = "İptal"
                        },
                        new
                        {
                            Id = 75,
                            Code = "PRODUCT.ADD.TITLE",
                            LangId = 2,
                            Value = "Add New Product"
                        },
                        new
                        {
                            Id = 76,
                            Code = "PRODUCT.NAME",
                            LangId = 2,
                            Value = "Product Name"
                        },
                        new
                        {
                            Id = 77,
                            Code = "PRODUCT.PRICE",
                            LangId = 2,
                            Value = "Price"
                        },
                        new
                        {
                            Id = 78,
                            Code = "PRODUCT.STOCK",
                            LangId = 2,
                            Value = "Stock"
                        },
                        new
                        {
                            Id = 79,
                            Code = "PRODUCT.COLORS",
                            LangId = 2,
                            Value = "Colors"
                        },
                        new
                        {
                            Id = 80,
                            Code = "PRODUCT.COLOR_NAME",
                            LangId = 2,
                            Value = "Color Name"
                        },
                        new
                        {
                            Id = 81,
                            Code = "PRODUCT.ADD_COLOR",
                            LangId = 2,
                            Value = "Add Color"
                        },
                        new
                        {
                            Id = 82,
                            Code = "VALIDATION.NAME_REQUIRED",
                            LangId = 2,
                            Value = "Product name is required"
                        },
                        new
                        {
                            Id = 83,
                            Code = "VALIDATION.PRICE_INVALID",
                            LangId = 2,
                            Value = "Please enter a valid price"
                        },
                        new
                        {
                            Id = 84,
                            Code = "VALIDATION.STOCK_INVALID",
                            LangId = 2,
                            Value = "Please enter a valid stock quantity"
                        },
                        new
                        {
                            Id = 85,
                            Code = "GENERAL.SAVE",
                            LangId = 2,
                            Value = "Save"
                        },
                        new
                        {
                            Id = 86,
                            Code = "GENERAL.CANCEL",
                            LangId = 2,
                            Value = "Cancel"
                        },
                        new
                        {
                            Id = 87,
                            Code = "PRODUCT.DETAIL.TITLE",
                            LangId = 1,
                            Value = "Ürün Detayı"
                        },
                        new
                        {
                            Id = 88,
                            Code = "GENERAL.LOADING",
                            LangId = 1,
                            Value = "Yükleniyor"
                        },
                        new
                        {
                            Id = 89,
                            Code = "PRODUCT.ID",
                            LangId = 1,
                            Value = "Ürün ID"
                        },
                        new
                        {
                            Id = 90,
                            Code = "PRODUCT.COLOR",
                            LangId = 1,
                            Value = "Renk"
                        },
                        new
                        {
                            Id = 91,
                            Code = "PRODUCT.NO_COLORS",
                            LangId = 1,
                            Value = "Tanımlı renk yok"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GENERAL.UPDATE",
                            LangId = 1,
                            Value = "Güncelle"
                        },
                        new
                        {
                            Id = 93,
                            Code = "GENERAL.BACK_TO_LIST",
                            LangId = 1,
                            Value = "Listeye Dön"
                        },
                        new
                        {
                            Id = 94,
                            Code = "PRODUCT.DETAIL.TITLE",
                            LangId = 2,
                            Value = "Product Detail"
                        },
                        new
                        {
                            Id = 95,
                            Code = "GENERAL.LOADING",
                            LangId = 2,
                            Value = "Loading"
                        },
                        new
                        {
                            Id = 96,
                            Code = "PRODUCT.ID",
                            LangId = 2,
                            Value = "Product ID"
                        },
                        new
                        {
                            Id = 97,
                            Code = "PRODUCT.COLOR",
                            LangId = 2,
                            Value = "Color"
                        },
                        new
                        {
                            Id = 98,
                            Code = "PRODUCT.NO_COLORS",
                            LangId = 2,
                            Value = "No colors defined"
                        },
                        new
                        {
                            Id = 99,
                            Code = "GENERAL.UPDATE",
                            LangId = 2,
                            Value = "Update"
                        },
                        new
                        {
                            Id = 100,
                            Code = "GENERAL.BACK_TO_LIST",
                            LangId = 2,
                            Value = "Back to List"
                        },
                        new
                        {
                            Id = 101,
                            Code = "PRODUCT.LIST.TITLE",
                            LangId = 1,
                            Value = "Ürün Listesi"
                        },
                        new
                        {
                            Id = 102,
                            Code = "GENERAL.RELOAD",
                            LangId = 1,
                            Value = "Yenile"
                        },
                        new
                        {
                            Id = 103,
                            Code = "GENERAL.ADD_NEW",
                            LangId = 1,
                            Value = "Yeni Ekle"
                        },
                        new
                        {
                            Id = 104,
                            Code = "GENERAL.SEARCH_PLACEHOLDER",
                            LangId = 1,
                            Value = "Ara..."
                        },
                        new
                        {
                            Id = 105,
                            Code = "GENERAL.NO_DATA_AVAILABLE",
                            LangId = 1,
                            Value = "Gösterilecek veri yok"
                        },
                        new
                        {
                            Id = 106,
                            Code = "PRODUCT.LIST.EXPORT_FILENAME",
                            LangId = 1,
                            Value = "urunler"
                        },
                        new
                        {
                            Id = 107,
                            Code = "ID",
                            LangId = 1,
                            Value = "ID"
                        },
                        new
                        {
                            Id = 108,
                            Code = "GENERAL.ACTIONS",
                            LangId = 1,
                            Value = "İşlemler"
                        },
                        new
                        {
                            Id = 109,
                            Code = "PRODUCT.LIST.TOTAL",
                            LangId = 1,
                            Value = "Toplam: {0}"
                        },
                        new
                        {
                            Id = 110,
                            Code = "GENERAL.DETAIL",
                            LangId = 1,
                            Value = "Detay"
                        },
                        new
                        {
                            Id = 111,
                            Code = "PRODUCT.LIST.TITLE",
                            LangId = 2,
                            Value = "Product List"
                        },
                        new
                        {
                            Id = 112,
                            Code = "GENERAL.RELOAD",
                            LangId = 2,
                            Value = "Reload"
                        },
                        new
                        {
                            Id = 113,
                            Code = "GENERAL.ADD_NEW",
                            LangId = 2,
                            Value = "Add New"
                        },
                        new
                        {
                            Id = 114,
                            Code = "GENERAL.SEARCH_PLACEHOLDER",
                            LangId = 2,
                            Value = "Search..."
                        },
                        new
                        {
                            Id = 115,
                            Code = "GENERAL.NO_DATA_AVAILABLE",
                            LangId = 2,
                            Value = "No data available"
                        },
                        new
                        {
                            Id = 116,
                            Code = "PRODUCT.LIST.EXPORT_FILENAME",
                            LangId = 2,
                            Value = "products"
                        },
                        new
                        {
                            Id = 117,
                            Code = "ID",
                            LangId = 2,
                            Value = "ID"
                        },
                        new
                        {
                            Id = 118,
                            Code = "GENERAL.ACTIONS",
                            LangId = 2,
                            Value = "Actions"
                        },
                        new
                        {
                            Id = 119,
                            Code = "PRODUCT.LIST.TOTAL",
                            LangId = 2,
                            Value = "Total: {0}"
                        },
                        new
                        {
                            Id = 120,
                            Code = "GENERAL.DETAIL",
                            LangId = 2,
                            Value = "Detail"
                        },
                        new
                        {
                            Id = 121,
                            Code = "PRODUCT.UPDATE.TITLE",
                            LangId = 1,
                            Value = "Ürünü Güncelle"
                        },
                        new
                        {
                            Id = 122,
                            Code = "PRODUCT.UPDATE.TITLE",
                            LangId = 2,
                            Value = "Update Product"
                        },
                        new
                        {
                            Id = 123,
                            Code = "DASHBOARD.SUMMARY",
                            LangId = 1,
                            Value = "Özet"
                        },
                        new
                        {
                            Id = 124,
                            Code = "DASHBOARD.TITLE",
                            LangId = 1,
                            Value = "Kontrol Paneli"
                        },
                        new
                        {
                            Id = 125,
                            Code = "DASHBOARD.WELCOME_TITLE",
                            LangId = 1,
                            Value = "Hoş geldiniz"
                        },
                        new
                        {
                            Id = 126,
                            Code = "DASHBOARD.SUMMARY_TEXT",
                            LangId = 1,
                            Value = "Sistemin genel durumunu buradan görüntüleyebilirsiniz."
                        },
                        new
                        {
                            Id = 127,
                            Code = "DASHBOARD.SUMMARY",
                            LangId = 2,
                            Value = "Summary"
                        },
                        new
                        {
                            Id = 128,
                            Code = "DASHBOARD.TITLE",
                            LangId = 2,
                            Value = "Dashboard"
                        },
                        new
                        {
                            Id = 129,
                            Code = "DASHBOARD.WELCOME_TITLE",
                            LangId = 2,
                            Value = "Welcome"
                        },
                        new
                        {
                            Id = 130,
                            Code = "DASHBOARD.SUMMARY_TEXT",
                            LangId = 2,
                            Value = "You can view the overall system status here."
                        },
                        new
                        {
                            Id = 131,
                            Code = "GroupList",
                            LangId = 1,
                            Value = "Grup Listesi"
                        },
                        new
                        {
                            Id = 132,
                            Code = "Add",
                            LangId = 1,
                            Value = "Ekle"
                        },
                        new
                        {
                            Id = 133,
                            Code = "Filter",
                            LangId = 1,
                            Value = "Filtrele"
                        },
                        new
                        {
                            Id = 134,
                            Code = "Id",
                            LangId = 1,
                            Value = "ID"
                        },
                        new
                        {
                            Id = 135,
                            Code = "GroupName",
                            LangId = 1,
                            Value = "Grup Adı"
                        },
                        new
                        {
                            Id = 136,
                            Code = "Actions",
                            LangId = 1,
                            Value = "İşlemler"
                        },
                        new
                        {
                            Id = 137,
                            Code = "GrupPermissions",
                            LangId = 1,
                            Value = "Grup Yetkileri"
                        },
                        new
                        {
                            Id = 138,
                            Code = "UsersGroups",
                            LangId = 1,
                            Value = "Kullanıcı Grupları"
                        },
                        new
                        {
                            Id = 139,
                            Code = "Update",
                            LangId = 1,
                            Value = "Güncelle"
                        },
                        new
                        {
                            Id = 140,
                            Code = "Delete",
                            LangId = 1,
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 141,
                            Code = "GroupForm",
                            LangId = 1,
                            Value = "Grup Formu"
                        },
                        new
                        {
                            Id = 142,
                            Code = "Required",
                            LangId = 1,
                            Value = "Zorunlu alan"
                        },
                        new
                        {
                            Id = 143,
                            Code = "Save",
                            LangId = 1,
                            Value = "Kaydet"
                        },
                        new
                        {
                            Id = 144,
                            Code = "GroupUsers",
                            LangId = 1,
                            Value = "Grup Kullanıcıları"
                        },
                        new
                        {
                            Id = 145,
                            Code = "Users",
                            LangId = 1,
                            Value = "Kullanıcılar"
                        },
                        new
                        {
                            Id = 146,
                            Code = "GroupClaims",
                            LangId = 1,
                            Value = "Grup Yetkileri"
                        },
                        new
                        {
                            Id = 147,
                            Code = "Claims",
                            LangId = 1,
                            Value = "Yetkiler"
                        },
                        new
                        {
                            Id = 148,
                            Code = "DeleteConfirm",
                            LangId = 1,
                            Value = "Bu grubu silmek istediğinize emin misiniz?"
                        },
                        new
                        {
                            Id = 149,
                            Code = "Cancel",
                            LangId = 1,
                            Value = "İptal"
                        },
                        new
                        {
                            Id = 150,
                            Code = "OK",
                            LangId = 1,
                            Value = "Tamam"
                        },
                        new
                        {
                            Id = 151,
                            Code = "GroupList",
                            LangId = 2,
                            Value = "Group List"
                        },
                        new
                        {
                            Id = 152,
                            Code = "Add",
                            LangId = 2,
                            Value = "Add"
                        },
                        new
                        {
                            Id = 153,
                            Code = "Filter",
                            LangId = 2,
                            Value = "Filter"
                        },
                        new
                        {
                            Id = 154,
                            Code = "Id",
                            LangId = 2,
                            Value = "ID"
                        },
                        new
                        {
                            Id = 155,
                            Code = "GroupName",
                            LangId = 2,
                            Value = "Group Name"
                        },
                        new
                        {
                            Id = 156,
                            Code = "Actions",
                            LangId = 2,
                            Value = "Actions"
                        },
                        new
                        {
                            Id = 157,
                            Code = "GrupPermissions",
                            LangId = 2,
                            Value = "Group Permissions"
                        },
                        new
                        {
                            Id = 158,
                            Code = "UsersGroups",
                            LangId = 2,
                            Value = "User Groups"
                        },
                        new
                        {
                            Id = 159,
                            Code = "Update",
                            LangId = 2,
                            Value = "Update"
                        },
                        new
                        {
                            Id = 160,
                            Code = "Delete",
                            LangId = 2,
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 161,
                            Code = "GroupForm",
                            LangId = 2,
                            Value = "Group Form"
                        },
                        new
                        {
                            Id = 162,
                            Code = "Required",
                            LangId = 2,
                            Value = "Required field"
                        },
                        new
                        {
                            Id = 163,
                            Code = "Save",
                            LangId = 2,
                            Value = "Save"
                        },
                        new
                        {
                            Id = 164,
                            Code = "GroupUsers",
                            LangId = 2,
                            Value = "Group Users"
                        },
                        new
                        {
                            Id = 165,
                            Code = "Users",
                            LangId = 2,
                            Value = "Users"
                        },
                        new
                        {
                            Id = 166,
                            Code = "GroupClaims",
                            LangId = 2,
                            Value = "Group Claims"
                        },
                        new
                        {
                            Id = 167,
                            Code = "Claims",
                            LangId = 2,
                            Value = "Claims"
                        },
                        new
                        {
                            Id = 168,
                            Code = "DeleteConfirm",
                            LangId = 2,
                            Value = "Are you sure you want to delete this group?"
                        },
                        new
                        {
                            Id = 169,
                            Code = "Cancel",
                            LangId = 2,
                            Value = "Cancel"
                        },
                        new
                        {
                            Id = 170,
                            Code = "OK",
                            LangId = 2,
                            Value = "OK"
                        },
                        new
                        {
                            Id = 171,
                            Code = "LanguageList",
                            LangId = 1,
                            Value = "Dil Listesi"
                        },
                        new
                        {
                            Id = 172,
                            Code = "Id",
                            LangId = 1,
                            Value = "ID"
                        },
                        new
                        {
                            Id = 173,
                            Code = "Name",
                            LangId = 1,
                            Value = "Ad"
                        },
                        new
                        {
                            Id = 174,
                            Code = "Code",
                            LangId = 1,
                            Value = "Kod"
                        },
                        new
                        {
                            Id = 175,
                            Code = "LanguageForm",
                            LangId = 1,
                            Value = "Dil Formu"
                        },
                        new
                        {
                            Id = 176,
                            Code = "FullName",
                            LangId = 1,
                            Value = "Tam Ad"
                        },
                        new
                        {
                            Id = 177,
                            Code = "LanguageList",
                            LangId = 2,
                            Value = "Language List"
                        },
                        new
                        {
                            Id = 178,
                            Code = "Id",
                            LangId = 2,
                            Value = "ID"
                        },
                        new
                        {
                            Id = 179,
                            Code = "Name",
                            LangId = 2,
                            Value = "Name"
                        },
                        new
                        {
                            Id = 180,
                            Code = "Code",
                            LangId = 2,
                            Value = "Code"
                        },
                        new
                        {
                            Id = 181,
                            Code = "LanguageForm",
                            LangId = 2,
                            Value = "Language Form"
                        },
                        new
                        {
                            Id = 182,
                            Code = "FullName",
                            LangId = 2,
                            Value = "Full Name"
                        },
                        new
                        {
                            Id = 183,
                            Code = "LogList",
                            LangId = 1,
                            Value = "Log Listesi"
                        },
                        new
                        {
                            Id = 184,
                            Code = "Level",
                            LangId = 1,
                            Value = "Seviye"
                        },
                        new
                        {
                            Id = 185,
                            Code = "ExceptionMessage",
                            LangId = 1,
                            Value = "Hata Mesajı"
                        },
                        new
                        {
                            Id = 186,
                            Code = "TimeStamp",
                            LangId = 1,
                            Value = "Zaman Damgası"
                        },
                        new
                        {
                            Id = 187,
                            Code = "User",
                            LangId = 1,
                            Value = "Kullanıcı"
                        },
                        new
                        {
                            Id = 188,
                            Code = "Value",
                            LangId = 1,
                            Value = "Değer"
                        },
                        new
                        {
                            Id = 189,
                            Code = "Type",
                            LangId = 1,
                            Value = "Tür"
                        },
                        new
                        {
                            Id = 190,
                            Code = "LogList",
                            LangId = 2,
                            Value = "Log List"
                        },
                        new
                        {
                            Id = 191,
                            Code = "Level",
                            LangId = 2,
                            Value = "Level"
                        },
                        new
                        {
                            Id = 192,
                            Code = "ExceptionMessage",
                            LangId = 2,
                            Value = "Exception Message"
                        },
                        new
                        {
                            Id = 193,
                            Code = "TimeStamp",
                            LangId = 2,
                            Value = "Timestamp"
                        },
                        new
                        {
                            Id = 194,
                            Code = "User",
                            LangId = 2,
                            Value = "User"
                        },
                        new
                        {
                            Id = 195,
                            Code = "Value",
                            LangId = 2,
                            Value = "Value"
                        },
                        new
                        {
                            Id = 196,
                            Code = "Type",
                            LangId = 2,
                            Value = "Type"
                        },
                        new
                        {
                            Id = 197,
                            Code = "OperationClaimList",
                            LangId = 1,
                            Value = "Yetki Listesi"
                        },
                        new
                        {
                            Id = 198,
                            Code = "Alias",
                            LangId = 1,
                            Value = "Kısa Ad"
                        },
                        new
                        {
                            Id = 199,
                            Code = "Description",
                            LangId = 1,
                            Value = "Açıklama"
                        },
                        new
                        {
                            Id = 200,
                            Code = "OperationClaimForm",
                            LangId = 1,
                            Value = "Yetki Formu"
                        },
                        new
                        {
                            Id = 201,
                            Code = "OperationClaimList",
                            LangId = 2,
                            Value = "Operation Claim List"
                        },
                        new
                        {
                            Id = 202,
                            Code = "Alias",
                            LangId = 2,
                            Value = "Alias"
                        },
                        new
                        {
                            Id = 203,
                            Code = "Description",
                            LangId = 2,
                            Value = "Description"
                        },
                        new
                        {
                            Id = 204,
                            Code = "OperationClaimForm",
                            LangId = 2,
                            Value = "Operation Claim Form"
                        },
                        new
                        {
                            Id = 205,
                            Code = "TranslateList",
                            LangId = 1,
                            Value = "Çeviri Listesi"
                        },
                        new
                        {
                            Id = 206,
                            Code = "LangCode",
                            LangId = 1,
                            Value = "Dil Kodu"
                        },
                        new
                        {
                            Id = 207,
                            Code = "TranslateForm",
                            LangId = 1,
                            Value = "Çeviri Formu"
                        },
                        new
                        {
                            Id = 208,
                            Code = "TranslateList",
                            LangId = 2,
                            Value = "Translation List"
                        },
                        new
                        {
                            Id = 209,
                            Code = "LangCode",
                            LangId = 2,
                            Value = "Language Code"
                        },
                        new
                        {
                            Id = 210,
                            Code = "TranslateForm",
                            LangId = 2,
                            Value = "Translation Form"
                        },
                        new
                        {
                            Id = 211,
                            Code = "UserList",
                            LangId = 1,
                            Value = "Kullanıcı Listesi"
                        },
                        new
                        {
                            Id = 212,
                            Code = "UserForm",
                            LangId = 1,
                            Value = "Kullanıcı Formu"
                        },
                        new
                        {
                            Id = 213,
                            Code = "ChangePassword",
                            LangId = 1,
                            Value = "Şifre Değiştir"
                        },
                        new
                        {
                            Id = 214,
                            Code = "UsersClaims",
                            LangId = 1,
                            Value = "Kullanıcı Yetkileri"
                        },
                        new
                        {
                            Id = 215,
                            Code = "Permissions",
                            LangId = 1,
                            Value = "Yetkiler"
                        },
                        new
                        {
                            Id = 216,
                            Code = "Groups",
                            LangId = 1,
                            Value = "Gruplar"
                        },
                        new
                        {
                            Id = 217,
                            Code = "Status",
                            LangId = 1,
                            Value = "Durum"
                        },
                        new
                        {
                            Id = 218,
                            Code = "MobilePhones",
                            LangId = 1,
                            Value = "Cep Telefonları"
                        },
                        new
                        {
                            Id = 219,
                            Code = "Address",
                            LangId = 1,
                            Value = "Adres"
                        },
                        new
                        {
                            Id = 220,
                            Code = "Notes",
                            LangId = 1,
                            Value = "Notlar"
                        },
                        new
                        {
                            Id = 221,
                            Code = "UserList",
                            LangId = 2,
                            Value = "User List"
                        },
                        new
                        {
                            Id = 222,
                            Code = "UserForm",
                            LangId = 2,
                            Value = "User Form"
                        },
                        new
                        {
                            Id = 223,
                            Code = "ChangePassword",
                            LangId = 2,
                            Value = "Change Password"
                        },
                        new
                        {
                            Id = 224,
                            Code = "UsersClaims",
                            LangId = 2,
                            Value = "Users' Claims"
                        },
                        new
                        {
                            Id = 225,
                            Code = "Permissions",
                            LangId = 2,
                            Value = "Permissions"
                        },
                        new
                        {
                            Id = 226,
                            Code = "Groups",
                            LangId = 2,
                            Value = "Groups"
                        },
                        new
                        {
                            Id = 227,
                            Code = "Status",
                            LangId = 2,
                            Value = "Status"
                        },
                        new
                        {
                            Id = 228,
                            Code = "MobilePhones",
                            LangId = 2,
                            Value = "Mobile Phones"
                        },
                        new
                        {
                            Id = 229,
                            Code = "Address",
                            LangId = 2,
                            Value = "Address"
                        },
                        new
                        {
                            Id = 230,
                            Code = "Notes",
                            LangId = 2,
                            Value = "Notes"
                        },
                        new
                        {
                            Id = 231,
                            Code = "Products",
                            LangId = 1,
                            Value = "Ürünler"
                        },
                        new
                        {
                            Id = 232,
                            Code = "Products",
                            LangId = 2,
                            Value = "Products"
                        },
                        new
                        {
                            Id = 233,
                            Code = "Product Add",
                            LangId = 1,
                            Value = "Ürün Ekle"
                        },
                        new
                        {
                            Id = 234,
                            Code = "Product Add",
                            LangId = 2,
                            Value = "Product Add"
                        },
                        new
                        {
                            Id = 235,
                            Code = "Product Detail",
                            LangId = 1,
                            Value = "Ürün Ayrıntıları"
                        },
                        new
                        {
                            Id = 236,
                            Code = "Product Detail",
                            LangId = 2,
                            Value = "Product Details"
                        },
                        new
                        {
                            Id = 237,
                            Code = "Product Detail",
                            LangId = 1,
                            Value = "Ürün Güncelle"
                        },
                        new
                        {
                            Id = 238,
                            Code = "Product Detail",
                            LangId = 2,
                            Value = "Product Update"
                        },
                        new
                        {
                            Id = 239,
                            Code = "Operation Claim",
                            LangId = 1,
                            Value = "Yetki"
                        },
                        new
                        {
                            Id = 240,
                            Code = "Operation Claim",
                            LangId = 2,
                            Value = "Operation Claim"
                        },
                        new
                        {
                            Id = 241,
                            Code = "Languages",
                            LangId = 1,
                            Value = "Diller"
                        },
                        new
                        {
                            Id = 242,
                            Code = "Languages",
                            LangId = 2,
                            Value = "Languages"
                        },
                        new
                        {
                            Id = 243,
                            Code = "Translations",
                            LangId = 1,
                            Value = "Çeviriler"
                        },
                        new
                        {
                            Id = 244,
                            Code = "Translations",
                            LangId = 2,
                            Value = "Translations"
                        },
                        new
                        {
                            Id = 245,
                            Code = "Logs",
                            LangId = 1,
                            Value = "İzleme Kayıtları"
                        },
                        new
                        {
                            Id = 246,
                            Code = "Logs",
                            LangId = 2,
                            Value = "Logs"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<long?>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MobilePhones")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateContactDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MobilePhones")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Concrete.UserClaim", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Entities.Concrete.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Entities.Concrete.Color", b =>
                {
                    b.HasOne("Entities.Concrete.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Concrete.GroupClaim", b =>
                {
                    b.HasOne("Entities.Concrete.Group", "Group")
                        .WithMany("GroupClaims")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.OperationClaim", "OperationClaim")
                        .WithMany("GroupClaims")
                        .HasForeignKey("OperationClaimId");

                    b.Navigation("Group");

                    b.Navigation("OperationClaim");
                });

            modelBuilder.Entity("Entities.Concrete.Translate", b =>
                {
                    b.HasOne("Entities.Concrete.Language", "Languages")
                        .WithMany("Translates")
                        .HasForeignKey("LanguagesId");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("Entities.Concrete.UserClaim", b =>
                {
                    b.HasOne("Entities.Concrete.OperationClaim", "Claim")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Concrete.UserGroup", b =>
                {
                    b.HasOne("Entities.Concrete.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Concrete.Group", b =>
                {
                    b.Navigation("GroupClaims");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Entities.Concrete.Language", b =>
                {
                    b.Navigation("Translates");
                });

            modelBuilder.Entity("Entities.Concrete.OperationClaim", b =>
                {
                    b.Navigation("GroupClaims");

                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("Entities.Concrete.Product", b =>
                {
                    b.Navigation("Colors");
                });

            modelBuilder.Entity("Entities.Concrete.User", b =>
                {
                    b.Navigation("UserClaims");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
